### ISSUE TITLE
overview.html als GitHub Pages 

### ISSUE THREAD

**Issue by littleyoda** [faiteanu/JavaStockQuotes#1]
Kannst du die overview.html als GitHub Page zur Verfügung stellen?

Bislang nutze ich für die Darstellung von HTML Seiten den Dienst rawgit.com, aber der Dienst ist nicht mehr verfügbar.

**Comment by faiteanu** [comment]
Die Seite ist nun unter folgender Adresse erreichbar:
https://faiteanu.github.io/JavaStockQuotes/
