### ISSUE TITLE
Kursabruf nur CSV (via Datei/Url import) verfügbar

### ISSUE THREAD

**Issue by Lupo135** [faiteanu/JavaStockQuotes#10]
Wenn ich im Depotviewer für ein Wertpapier "Aktualisieren (Einstellung wählen).."anklicke, bekomme ich als Auswahl nur CSV (via Datei bzw. Url) angeboten.  Ich habe die Dateien ariva.js und finanzennet.js wie beschrieben unter hibiscus.depotviewer\js kopiert und in ariva.js meine Login Daten eingetragen. 
Was mache ich falsch?
Muss ariva.js in Einstellungen->Scripting eingetragen werden?

**Comment by faiteanu** [comment]
Hast du die neueste Version von Jameica / Hibiscus / DepotViewer installiert?
Ich habe es bei mir gerade ausprobiert: unter Aktualisieren wurde mir Ariva angezeigt. Dann habe ich die Datei `portfolioreport.js` auch in den Ordner `hibiscus.depotviewer\js` kopiert, Jameica neu gestartet, und es gab einen neuen Eintrag `PortfolioReport` im Aktualisieren-Dialog. 
Überprüfe daher bitte nochmal, ob die restliche Software aktuell ist und du tatsächlich den richtigen Ordner verwendest. Man muss sonst nichts konfigurieren oder einstellen.

**Comment by Lupo135** [comment]
Ich habe überall die neueste Version.
Bei der Installation habe ich nicht das Standardverzeichnis "C:\Users\franz\.jameica" verwendet, sondern "D:\EigeneDaten\Bank\Hibiscus". Weil ariva nicht auswählbar war, habe ich dann Jameica-Hibiscus wieder deinstalliert, das Installationsverzeichnis gelöscht und dann nochmal installiert. Bei dieser Installation wurde nicht mehr nach dem Verzeichnis gefragt sondern automatisch das bei der ersten Installation verwendete Verzeichnis verwendet. Mir ist unklar, wo das System sich das gemerkt hat. Ich habe dann das Verzeichnis nach "C:\Users\franz\.jameica" gewechselt und dann die Plugins dort nochmal neu installiert. Hat aber alles nicht geholfen. Langsam verzweifle ich.

**Comment by faiteanu** [comment]
Das scheint irgendwie nicht ganz richtig gelaufen zu sein. Wenn man den [Installer](https://hibiscus-mashup.derrichter.de/index.php/download) verwendet, wird Jameica unter `C:\Program Files\Jameica` installiert. Es gibt dann zusätzlich ein Benutzerverzeichnis, welches bei dir unter `C:\Users\franz\.jameica` liegen dürfte. Kann es sein, dass in deinem Pfad der Schrägstrich hinter `franz` fehlte?
Für derartige Fragen zur Installation von Jameica würde ich auf das [Homebanking-Forum](https://homebanking-hilfe.de/forum/index.php?f=33) verweisen. Die Leute dort wissen bestimmt besser, wie man das Installations- und/oder Benutzerverzeichnis ändern kann.

**Comment by Lupo135** [comment]
Ich habe mir zur Installation jetzt die Zip-Version heruntergeladen und in eine neues Verzeichnis gelegt. Wenn ich dort die jameica-win64.exe starte sehe ich jetzt ariva. Bei aktualisieren der Kurse gibt es aber noch einen Fehler. Den Login habe ich in ariva.js eingetragen. 
Die Fehlermeldung:
23.04.2024 19:26:40] Starte mit DE000BASF111
[23.04.2024 19:27:03] TypeError: options.get(i).includes is not a function in <eval> at line number 92
[23.04.2024 19:27:03] Fehler beim Abruf der Kurse.

Der backslash hinter franz\.jameica ist vorhanden. War nur ein Tippfehler bei meiner Anfrage.

**Comment by Lupo135** [comment]
Wenn ich portfolioreport auswähle funktioniert der Abruf.
Bei WKN 728317 geht auch ariva.

**Comment by faiteanu** [comment]
Der Fehler hängt damit zusammen, dass das Ariva Skript zuletzt "repariert" wurde, die entsprechende Änderung aber noch nicht im DepotViewer eingebaut ist: https://github.com/littleyoda/hibiscus.depotviewer/issues/131

Du kannst versuchen, die dort verlinkte Bibliothek `java-stock-quotes-0.1.4.jar` in den Ordner `.jameica\plugins\hibiscus.depotviewer\lib` zu schreiben, und dafür die Datei `java-stock-quotes-0.1.2.jar` zu löschen.
Es ist zwar nicht schön, das manuell machen zu müssen, aber es sind nunmal verschiedene Entwickler und verschiedene Programme/Bibliotheken beteiligt.

**Comment by Lupo135** [comment]
Jetzt geht´s. Vielen Dank!
