### ISSUE TITLE
Fehler beim Abruf der Kurse

### ISSUE THREAD

**Issue by GralfR** [faiteanu/JavaStockQuotes#11]
Seit Mitte August kann der Depotviewer einige Kurse nicht mehr abrufen, andere funktionieren aber noch.
Ich habe ein Ariva-Konto und bis 13.8. haben alle meine Wertpapiere funktioniert. Nun gehen einige nicht mehr. Beim Versuch, den aktuellen Kurs abzurufen, erhalte ich in der Statusanzeige:
```
[01.09.2024 08:39:45] Starte mit US67066G1040
[01.09.2024 08:39:50] Speichern
[01.09.2024 08:39:50] Fehler beim Abruf der Kurse.
```
Betroffene Wertpapiere sind bei mir mind.
- ISIN US67066G1040 (NVIDIA)
- ISIN US88160R1014 (Tesla)
- ISIN XC0009655157 (Feingold)

Funktionieren tut z.B.
- ISIN LU0275317336

Mein Ariva-Konto und Script funktioniert also generell. Und manuell auf Ariva.de finde ich auch die Kurse der betroffenen Papiere. Irgendeine Feinheit stimmt also nicht bei diesen Papieren. Vielleicht ein Filter nicht genau genug? Die betroffenen Werte sind Einzelaktien, während die funktionierenden Fonds sind. Vielleicht hat das damit etwas zu tun?

Kann das Problem jemand bestätigen oder widerlegen?
Danke

**Comment by justr1** [comment]
Das gleiche Problem hatte ich nach dem letzten DepotViewer-Update auch. Ich war bisher wegen des DepotViewers in jameica noch auf Java11 unterwegs. Mit Java17 musste ich dann aber auch noch Ariva.js auf die letzte Version (2024-04-04) aktualisieren und seitdem läuft alles. Die gnampf1-Version mit dem Ariva-Login vom März reichte nicht.

**Comment by GralfR** [comment]
Vielen Dank. Funktioniert wieder.
