### ISSUE TITLE
Ariva broken

### ISSUE THREAD

**Issue by Stullemon** [faiteanu/JavaStockQuotes#2]
Hi, I realized it wasn't working anymore for Ariva. I always got an error like

 "404 Not Found for https://www.ariva.de/fonds/amundi_luxemb-123/historische_ereignisse?clean_split=0"

in Jameica DepotViewer. I tried to understand what was happening and when I changed the line 

`		eventUrl = url + "/historische_ereignisse?clean_split=0";			`
with
`		eventUrl = url + "/dividende-split?clean_split=0";			`
in the function extractEvents. This lets me resume updates but I am not 100 % sure if that is correct. Hence, I am not submitting a pull request at this time. :-)

**Comment by faiteanu** [comment]
Thanks for the information. I fixed the url for downloading historic events from Ariva. Although some ETFs seem to use a url like `/ausschuettungen`, `/dividende-split` redirected the request correctly.
