### ISSUE TITLE
request: script-update inside jameica

### ISSUE THREAD

**Issue by GralfR** [faiteanu/JavaStockQuotes#4]
Everytime I want to update stock values I need to update the script-file. 
This is some kind of problem, because it's hard to find the source. So I set a bookmark to [this](https://faiteanu.github.io/JavaStockQuotes/), which helped in any case so far.

But I wonder, if it was possible to include this update into the plugin-update-menu inside jameica. So I am reminded to update this script, too, and the download and installation is working with one click. That would improve the user-experience a lot.

**Comment by faiteanu** [comment]
> Everytime I want to update stock values I need to update the script-file.

That should not be necessary. It only needs to be updated when it has changed.

As explained in https://homebanking-hilfe.de/forum/topic.php?p=164261#real164261 it was a deliberate choice of the DepotViewer author not to include the script file in his plugin, to avoid legal issues. I'm afraid, there is not much I can do about it. The script itself is not a plugin of jameica, so it can't be updated using the jameica plugin infrastructure.
